// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef _VRVFPGASIM__SYMS_H_
#define _VRVFPGASIM__SYMS_H_  // guard

#include "verilated_heavy.h"

// INCLUDE MODULE CLASSES
#include "Vrvfpgasim.h"
#include "Vrvfpgasim_rvfpgasim.h"
#include "Vrvfpgasim___024unit.h"
#include "Vrvfpgasim_veerwolf_core__B0_Cbebc20.h"
#include "Vrvfpgasim_wb_mem_wrapper__M1000_I0.h"
#include "Vrvfpgasim_dpram64__S1000_MB0.h"
#include "Vrvfpgasim_axi_demux__pi3.h"
#include "Vrvfpgasim_axi_mux__pi5.h"
#include "Vrvfpgasim_el2_configurable_gw.h"
#include "Vrvfpgasim_axi_demux_id_counters__pi14.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS
class Vrvfpgasim__Syms : public VerilatedSyms {
  public:
    
    // LOCAL STATE
    const char* __Vm_namep;
    bool __Vm_activity;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode;  ///< Used by trace routines when tracing multiple models
    bool __Vm_didInit;
    
    // SUBCELL STATE
    Vrvfpgasim*                    TOPp;
    Vrvfpgasim_rvfpgasim           TOP__rvfpgasim;
    Vrvfpgasim_veerwolf_core__B0_Cbebc20 TOP__rvfpgasim__veerwolf;
    Vrvfpgasim_axi_mux__pi5        TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_mst_port_mux__BRA__0__KET____DOT__i_axi_mux;
    Vrvfpgasim_axi_mux__pi5        TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_mst_port_mux__BRA__1__KET____DOT__i_axi_mux;
    Vrvfpgasim_axi_demux__pi3      TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__0__KET____DOT__i_axi_demux;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__0__KET____DOT__i_axi_demux__gen_demux__DOT__i_ar_id_counter;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__0__KET____DOT__i_axi_demux__gen_demux__DOT__i_aw_id_counter;
    Vrvfpgasim_axi_demux__pi3      TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__1__KET____DOT__i_axi_demux;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__1__KET____DOT__i_axi_demux__gen_demux__DOT__i_ar_id_counter;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__1__KET____DOT__i_axi_demux__gen_demux__DOT__i_aw_id_counter;
    Vrvfpgasim_axi_demux__pi3      TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__2__KET____DOT__i_axi_demux;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__2__KET____DOT__i_axi_demux__gen_demux__DOT__i_ar_id_counter;
    Vrvfpgasim_axi_demux_id_counters__pi14 TOP__rvfpgasim__veerwolf__axi_intercon__DOT__axi_xbar__DOT__gen_slv_port_demux__BRA__2__KET____DOT__i_axi_demux__gen_demux__DOT__i_aw_id_counter;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__0__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__1__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__2__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__3__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__4__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__5__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__6__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__0__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__1__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__2__KET____DOT__gw_inst;
    Vrvfpgasim_el2_configurable_gw TOP__rvfpgasim__veerwolf__rvtop__DOT__veer__DOT__pic_ctrl_inst__DOT__IO_CLK_GRP__BRA__7__KET____DOT__GW__BRA__3__KET____DOT__gw_inst;
    Vrvfpgasim_wb_mem_wrapper__M1000_I0 TOP__rvfpgasim__veerwolf__bootrom;
    Vrvfpgasim_dpram64__S1000_MB0  TOP__rvfpgasim__veerwolf__bootrom__ram;
    
    // SCOPE NAMES
    VerilatedScope __Vscope_rvfpgasim__veerwolf__bootrom__ram;
    
    // CREATORS
    Vrvfpgasim__Syms(Vrvfpgasim* topp, const char* namep);
    ~Vrvfpgasim__Syms() {}
    
    // METHODS
    inline const char* name() { return __Vm_namep; }
    
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
